# type: ignore

"""add tables for ROA

Revision ID: 2c9cf71649e2
Revises: 5c02d93ce254
Create Date: 2021-08-10 11:26:10.569322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9cf71649e2'
down_revision = '5c02d93ce254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records_on_appeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date_filed', sa.DateTime(), nullable=True),
    sa.Column('sealed', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('court', sa.String(), nullable=True),
    sa.Column('receiving_court', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('remanded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_on_appeal_id'), 'records_on_appeal', ['id'], unique=False)
    op.create_table('roa_docket_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('court', sa.String(), nullable=False),
    sa.Column('recieving_court', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date_filed', sa.DateTime(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('sealed', sa.Boolean(), nullable=True),
    sa.Column('include_with_appeal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['records_on_appeal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roa_docket_entry')
    op.drop_index(op.f('ix_records_on_appeal_id'), table_name='records_on_appeal')
    op.drop_table('records_on_appeal')
    # ### end Alembic commands ###
