# type: ignore

"""Added status field to case

Revision ID: 400c04778408
Revises: a966106daa49
Create Date: 2021-07-27 14:55:37.803628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400c04778408'
down_revision = 'a966106daa49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'status')
    # ### end Alembic commands ###
