# type: ignore

"""add court_id to user table

Revision ID: 878d3f26cbfd
Revises: 2c9cf71649e2
Create Date: 2021-08-17 13:58:31.753872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878d3f26cbfd'
down_revision = '2c9cf71649e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('court_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'court_id')
    # ### end Alembic commands ###
