# type: ignore

"""Added court field to case

Revision ID: a966106daa49
Revises: 7426da0d030a
Create Date: 2021-07-26 16:36:14.756491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a966106daa49'
down_revision = '7426da0d030a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('court', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'court')
    # ### end Alembic commands ###
