courts = {
    'akb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Alaska',
            'parent': None,
            'short_name': 'D. Alaska'},
    'akd': {'type': 'district',
            'full_name': 'District Court, D. Alaska',
            'parent': 'ca9',
            'short_name': 'D. Alaska'},
    'almb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. Alabama',
             'parent': 'ca11',
             'short_name': 'M.D. Alabama'},
    'almd': {'type': 'district',
             'full_name': 'District Court, M.D. Alabama',
             'parent': 'ca11',
             'short_name': 'M.D. Alabama'},
    'alnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Alabama',
             'parent': None,
             'short_name': 'N.D. Alabama'},
    'alnd': {'type': 'district',
             'full_name': 'District Court, N.D. Alabama',
             'parent': 'ca11',
             'short_name': 'N.D. Alabama'},
    'alsb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Alabama',
             'parent': None,
             'short_name': 'S.D. Alabama'},
    'alsd': {'type': 'district',
             'full_name': 'District Court, S.D. Alabama',
             'parent': 'ca11',
             'short_name': 'S.D. Alabama'},
    'arb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Arizona',
            'parent': None,
            'short_name': 'D. Arizona'},
    'areb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Arkansas',
             'parent': None,
             'short_name': 'E.D. Arkansas'},
    'ared': {'type': 'district',
             'full_name': 'District Court, E.D. Arkansas',
             'parent': 'ca8',
             'short_name': 'E.D. Arkansas'},
    'arwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Arkansas',
             'parent': None,
             'short_name': 'W.D. Arkansas'},
    'arwd': {'type': 'district',
             'full_name': 'District Court, W.D. Arkansas',
             'parent': 'ca8',
             'short_name': 'W.D. Arkansas'},
    'azd': {'type': 'district',
            'full_name': 'District Court, D. Arizona',
            'parent': 'ca9',
            'short_name': 'D. Arizona'},
    'ca1': {'type': 'appellate',
            'full_name': 'Court of Appeals for the First Circuit',
            'parent': 'scotus',
            'short_name': 'First Circuit'},
    'ca10': {'type': 'appellate',
             'full_name': 'Court of Appeals for the Tenth Circuit',
             'parent': 'scotus',
             'short_name': 'Tenth Circuit'},
    'ca11': {'type': 'appellate',
             'full_name': 'Court of Appeals for the Eleventh Circuit',
             'parent': 'scotus',
             'short_name': 'Eleventh Circuit'},
    'ca2': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Second Circuit',
            'parent': 'scotus',
            'short_name': 'Second Circuit'},
    'ca3': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Third Circuit',
            'parent': 'scotus',
            'short_name': 'Third Circuit'},
    'ca4': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Fourth Circuit',
            'parent': 'scotus',
            'short_name': 'Fourth Circuit'},
    'ca5': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Fifth Circuit',
            'parent': 'scotus',
            'short_name': 'Fifth Circuit'},
    'ca6': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Sixth Circuit',
            'parent': 'scotus',
            'short_name': 'Sixth Circuit'},
    'ca7': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Seventh Circuit',
            'parent': 'scotus',
            'short_name': 'Seventh Circuit'},
    'ca8': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Eighth Circuit',
            'parent': 'scotus',
            'short_name': 'Eighth Circuit'},
    'ca9': {'type': 'appellate',
            'full_name': 'Court of Appeals for the Ninth Circuit',
            'parent': 'scotus',
            'short_name': 'Ninth Circuit'},
    'cacb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, C.D. California',
             'parent': None,
             'short_name': 'C.D. California'},
    'cacd': {'type': 'district',
             'full_name': 'District Court, C.D. California',
             'parent': 'ca9',
             'short_name': 'C.D. California'},
    'cadc': {'type': 'appellate',
             'full_name': 'Court of Appeals for the D.C. Circuit',
             'parent': 'scotus',
             'short_name': 'D.C. Circuit'},
    'caeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. California',
             'parent': None,
             'short_name': 'E.D. California'},
    'caed': {'type': 'district',
             'full_name': 'District Court, E.D. California',
             'parent': 'ca9',
             'short_name': 'E.D. California'},
    'cafc': {'type': 'appellate',
             'full_name': 'Court of Appeals for the Federal Circuit',
             'parent': 'scotus',
             'short_name': 'Federal Circuit'},
    'canb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. California',
             'parent': None,
             'short_name': 'N.D. California'},
    'cand': {'type': 'district',
             'full_name': 'District Court, N.D. California',
             'parent': 'ca9',
             'short_name': 'N.D. California'},
    'casb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. California',
             'parent': None,
             'short_name': 'S.D. California'},
    'casd': {'type': 'district',
             'full_name': 'District Court, S.D. California',
             'parent': 'ca9',
             'short_name': 'S.D. California'},
    'cob': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Colorado',
            'parent': None,
            'short_name': 'D. Colorado'},
    'cod': {'type': 'district',
            'full_name': 'District Court, D. Colorado',
            'parent': 'ca10',
            'short_name': 'D. Colorado'},
    'ctb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Connecticut',
            'parent': None,
            'short_name': 'D. Connecticut'},
    'ctd': {'type': 'district',
            'full_name': 'District Court, D. Connecticut',
            'parent': 'ca2',
            'short_name': 'D. Connecticut'},
    'dcb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, District of Columbia',
            'parent': None,
            'short_name': 'District of Columbia'},
    'dcd': {'type': 'district',
            'full_name': 'District Court, District of Columbia',
            'parent': 'cadc',
            'short_name': 'District of Columbia'},
    'deb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Delaware',
            'parent': None,
            'short_name': 'D. Delaware'},
    'ded': {'type': 'district',
            'full_name': 'District Court, D. Delaware',
            'parent': 'ca3',
            'short_name': 'D. Delaware'},
    'flmb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. Florida',
             'parent': None,
             'short_name': 'M.D. Florida'},
    'flmd': {'type': 'district',
             'full_name': 'District Court, M.D. Florida',
             'parent': 'ca11',
             'short_name': 'M.D. Florida'},
    'flnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Florida',
             'parent': None,
             'short_name': 'N.D. Florida'},
    'flnd': {'type': 'district',
             'full_name': 'District Court, N.D. Florida',
             'parent': 'ca11',
             'short_name': 'N.D. Florida'},
    'flsb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Florida.',
             'parent': None,
             'short_name': 'S.D. Florida'},
    'flsd': {'type': 'district',
             'full_name': 'District Court, S.D. Florida',
             'parent': 'ca11',
             'short_name': 'S.D. Florida'},
    'gamb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. Georgia',
             'parent': None,
             'short_name': 'M.D. Georgia'},
    'gamd': {'type': 'district',
             'full_name': 'District Court, M.D. Georgia',
             'parent': 'ca11',
             'short_name': 'M.D. Georgia'},
    'ganb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Georgia',
             'parent': None,
             'short_name': 'N.D. Georgia'},
    'gand': {'type': 'district',
             'full_name': 'District Court, N.D. Georgia',
             'parent': 'ca11',
             'short_name': 'N.D. Georgia'},
    'gasb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Georgia',
             'parent': None,
             'short_name': 'S.D. Georgia'},
    'gasd': {'type': 'district',
             'full_name': 'District Court, S.D. Georgia',
             'parent': 'ca11',
             'short_name': 'S.D. Georgia'},
    'gub': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Guam',
            'parent': None,
            'short_name': 'D. Guam'},
    'gud': {'type': 'district',
            'full_name': 'District Court, D. Guam',
            'parent': 'ca9',
            'short_name': 'D. Guam'},
    'hib': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Hawaii',
            'parent': None,
            'short_name': 'D. Hawaii'},
    'hid': {'type': 'district',
            'full_name': 'District Court, D. Hawaii',
            'parent': 'ca9',
            'short_name': 'D. Hawaii'},
    'ianb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Iowa',
             'parent': None,
             'short_name': 'N.D. Iowa'},
    'iand': {'type': 'district',
             'full_name': 'District Court, N.D. Iowa',
             'parent': 'ca8',
             'short_name': 'N.D. Iowa'},
    'iasb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Iowa',
             'parent': None,
             'short_name': 'S.D. Iowa'},
    'iasd': {'type': 'district',
             'full_name': 'District Court, S.D. Iowa',
             'parent': 'ca8',
             'short_name': 'S.D. Iowa'},
    'idb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Idaho',
            'parent': None,
            'short_name': 'D. Idaho'},
    'idd': {'type': 'district',
            'full_name': 'District Court, D. Idaho',
            'parent': 'ca9',
            'short_name': 'D. Idaho'},
    'ilcb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, C.D. Illinois',
             'parent': None,
             'short_name': 'C.D. Illinois'},
    'ilcd': {'type': 'district',
             'full_name': 'District Court, C.D. Illinois',
             'parent': 'ca7',
             'short_name': 'C.D. Illinois'},
    'ilnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Illinois',
             'parent': None,
             'short_name': 'N.D. Illinois'},
    'ilnd': {'type': 'district',
             'full_name': 'District Court, N.D. Illinois',
             'parent': 'ca7',
             'short_name': 'N.D. Illinois'},
    'ilsb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Illinois',
             'parent': None,
             'short_name': 'S.D. Illinois'},
    'ilsd': {'type': 'district',
             'full_name': 'District Court, S.D. Illinois',
             'parent': 'ca7',
             'short_name': 'S.D. Illinois'},
    'innb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Indiana',
             'parent': None,
             'short_name': 'N.D. Indiana'},
    'innd': {'type': 'district',
             'full_name': 'District Court, N.D. Indiana',
             'parent': 'ca7',
             'short_name': 'N.D. Indiana'},
    'insb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Indiana',
             'parent': None,
             'short_name': 'S.D. Indiana'},
    'insd': {'type': 'district',
             'full_name': 'District Court, S.D. Indiana',
             'parent': 'ca7',
             'short_name': 'S.D. Indiana'},
    'ksb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Kansas',
            'parent': None,
            'short_name': 'D. Kansas'},
    'ksd': {'type': 'district',
            'full_name': 'District Court, D. Kansas',
            'parent': 'ca10',
            'short_name': 'D. Kansas'},
    'kyeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Kentucky',
             'parent': None,
             'short_name': 'E.D. Kentucky'},
    'kyed': {'type': 'district',
             'full_name': 'District Court, E.D. Kentucky',
             'parent': 'ca6',
             'short_name': 'E.D. Kentucky'},
    'kywb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Kentucky',
             'parent': None,
             'short_name': 'W.D. Kentucky'},
    'kywd': {'type': 'district',
             'full_name': 'District Court, W.D. Kentucky',
             'parent': 'ca6',
             'short_name': 'W.D. Kentucky'},
    'laeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Louisiana',
             'parent': None,
             'short_name': 'E.D. Louisiana'},
    'laed': {'type': 'district',
             'full_name': 'District Court, E.D. Louisiana',
             'parent': 'ca5',
             'short_name': 'E.D. Louisiana'},
    'lamb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. Louisiana',
             'parent': None,
             'short_name': 'M.D. Louisiana'},
    'lamd': {'type': 'district',
             'full_name': 'District Court, M.D. Louisiana',
             'parent': 'ca5',
             'short_name': 'M.D. Louisiana'},
    'lawb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Louisiana',
             'parent': None,
             'short_name': 'W.D. Louisiana'},
    'lawd': {'type': 'district',
             'full_name': 'District Court, W.D. Louisiana',
             'parent': 'ca5',
             'short_name': 'W.D. Louisiana'},
    'mab': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Massachusetts',
            'parent': None,
            'short_name': 'D. Massachusetts'},
    'mad': {'type': 'district',
            'full_name': 'District Court, D. Massachusetts',
            'parent': 'ca1',
            'short_name': 'D. Massachusetts'},
    'mdb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Maryland',
            'parent': None,
            'short_name': 'D. Maryland'},
    'mdd': {'type': 'district',
            'full_name': 'District Court, D. Maryland',
            'parent': 'ca4',
            'short_name': 'D. Maryland'},
    'meb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Maine',
            'parent': None,
            'short_name': 'D. Maine'},
    'med': {'type': 'district',
            'full_name': 'District Court, D. Maine',
            'parent': 'ca1',
            'short_name': 'D. Maine'},
    'mieb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Michigan',
             'parent': None,
             'short_name': 'E.D. Michigan'},
    'mied': {'type': 'district',
             'full_name': 'District Court, E.D. Michigan',
             'parent': 'ca6',
             'short_name': 'E.D. Michigan'},
    'miwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Michigan',
             'parent': None,
             'short_name': 'W.D. Michigan'},
    'miwd': {'type': 'district',
             'full_name': 'District Court, W.D. Michigan',
             'parent': 'ca6',
             'short_name': 'W.D. Michigan'},
    'mnb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Minnesota',
            'parent': None,
            'short_name': 'D. Minnesota'},
    'mnd': {'type': 'district',
            'full_name': 'District Court, D. Minnesota',
            'parent': 'ca8',
            'short_name': 'D. Minnesota'},
    'moeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Missouri',
             'parent': None,
             'short_name': 'E.D. Missouri'},
    'moed': {'type': 'district',
             'full_name': 'District Court, E.D. Missouri',
             'parent': 'ca8',
             'short_name': 'E.D. Missouri'},
    'mowb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Missouri',
             'parent': None,
             'short_name': 'W.D. Missouri'},
    'mowd': {'type': 'district',
             'full_name': 'District Court, W.D. Missouri',
             'parent': 'ca8',
             'short_name': 'W.D. Missouri'},
    'msnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Mississippi',
             'parent': None,
             'short_name': 'N.D. Mississippi'},
    'msnd': {'type': 'district',
             'full_name': 'District Court, N.D. Mississippi',
             'parent': 'ca5',
             'short_name': 'N.D. Mississippi'},
    'mssb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Mississippi',
             'parent': None,
             'short_name': 'S.D. Mississippi'},
    'mssd': {'type': 'district',
             'full_name': 'District Court, S.D. Mississippi',
             'parent': 'ca5',
             'short_name': 'S.D. Mississippi'},
    'mtb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Montana',
            'parent': None,
            'short_name': 'D. Montana'},
    'mtd': {'type': 'district',
            'full_name': 'District Court, D. Montana',
            'parent': 'ca9',
            'short_name': 'D. Montana'},
    'nceb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. North Carolina',
             'parent': None,
             'short_name': 'E.D. North Carolina'},
    'nced': {'type': 'district',
             'full_name': 'District Court, E.D. North Carolina',
             'parent': 'ca4',
             'short_name': 'E.D. North Carolina'},
    'ncmb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. North Carolina',
             'parent': None,
             'short_name': 'M.D. North Carolina'},
    'ncmd': {'type': 'district',
             'full_name': 'District Court, M.D. North Carolina',
             'parent': 'ca4',
             'short_name': 'M.D. North Carolina'},
    'ncwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. North Carolina',
             'parent': None,
             'short_name': 'W.D. North Carolina'},
    'ncwd': {'type': 'district',
             'full_name': 'District Court, W.D. North Carolina',
             'parent': 'ca4',
             'short_name': 'W.D. North Carolina'},
    'ndb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. North Dakota',
            'parent': None,
            'short_name': 'D. North Dakota'},
    'ndd': {'type': 'district',
            'full_name': 'District Court, D. North Dakota',
            'parent': 'ca8',
            'short_name': 'D. North Dakota'},
    'nebraskab': {'type': 'bankruptcy',
                  'full_name': 'United States Bankruptcy Court, D. Nebraska',
                  'parent': None,
                  'short_name': 'D. Nebraska'},
    'ned': {'type': 'district',
            'full_name': 'District Court, D. Nebraska',
            'parent': 'ca8',
            'short_name': 'D. Nebraska'},
    'nhb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. New Hampshire',
            'parent': None,
            'short_name': 'D. New Hampshire'},
    'nhd': {'type': 'district',
            'full_name': 'District Court, D. New Hampshire',
            'parent': 'ca1',
            'short_name': 'D. New Hampshire'},
    'njb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. New Jersey',
            'parent': None,
            'short_name': 'D. New Jersey'},
    'njd': {'type': 'district',
            'full_name': 'District Court, D. New Jersey',
            'parent': 'ca3',
            'short_name': 'D. New Jersey'},
    'nmb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. New Mexico',
            'parent': None,
            'short_name': 'D. New Mexico'},
    'nmd': {'type': 'district',
            'full_name': 'District Court, D. New Mexico',
            'parent': 'ca10',
            'short_name': 'D. New Mexico'},
    'nmib': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, Northern Mariana '
             'Islands',
             'parent': None,
             'short_name': 'Northern Mariana Islands'},
    'nmid': {'type': 'district',
             'full_name': 'District Court, Northern Mariana Islands',
             'parent': 'ca9',
             'short_name': 'Northern Mariana Islands'},
    'nvb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Nevada',
            'parent': None,
            'short_name': 'D. Nevada'},
    'nvd': {'type': 'district',
            'full_name': 'District Court, D. Nevada',
            'parent': 'ca9',
            'short_name': 'D. Nevada'},
    'nyeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. New York',
             'parent': None,
             'short_name': 'E.D. New York'},
    'nyed': {'type': 'district',
             'full_name': 'District Court, E.D. New York',
             'parent': 'ca2',
             'short_name': 'E.D. New York'},
    'nynb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. New York',
             'parent': None,
             'short_name': 'N.D. New York'},
    'nynd': {'type': 'district',
             'full_name': 'District Court, N.D. New York',
             'parent': 'ca2',
             'short_name': 'N.D. New York'},
    'nysb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. New York',
             'parent': None,
             'short_name': 'S.D. New York'},
    'nysd': {'type': 'district',
             'full_name': 'District Court, S.D. New York',
             'parent': 'ca2',
             'short_name': 'S.D. New York'},
    'nywb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. New York',
             'parent': None,
             'short_name': 'W.D. New York'},
    'nywd': {'type': 'district',
             'full_name': 'District Court, W.D. New York',
             'parent': 'ca2',
             'short_name': 'W.D. New York'},
    'ohnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Ohio',
             'parent': None,
             'short_name': 'N.D. Ohio'},
    'ohnd': {'type': 'district',
             'full_name': 'District Court, N.D. Ohio',
             'parent': 'ca6',
             'short_name': 'N.D. Ohio'},
    'ohsb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Ohio',
             'parent': None,
             'short_name': 'S.D. Ohio'},
    'ohsd': {'type': 'district',
             'full_name': 'District Court, S.D. Ohio',
             'parent': 'ca6',
             'short_name': 'S.D. Ohio'},
    'okeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Oklahoma',
             'parent': None,
             'short_name': 'E.D. Oklahoma'},
    'oked': {'type': 'district',
             'full_name': 'District Court, E.D. Oklahoma',
             'parent': 'ca10',
             'short_name': 'E.D. Oklahoma'},
    'oknb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Oklahoma',
             'parent': None,
             'short_name': 'N.D. Oklahoma'},
    'oknd': {'type': 'district',
             'full_name': 'District Court, N.D. Oklahoma',
             'parent': 'ca10',
             'short_name': 'N.D. Oklahoma'},
    'okwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Oklahoma',
             'parent': None,
             'short_name': 'W.D. Oklahoma'},
    'okwd': {'type': 'district',
             'full_name': 'District Court, W.D. Oklahoma',
             'parent': 'ca10',
             'short_name': 'W.D. Oklahoma'},
    'orb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Oregon',
            'parent': None,
            'short_name': 'D. Oregon'},
    'ord': {'type': 'district',
            'full_name': 'District Court, D. Oregon',
            'parent': 'ca9',
            'short_name': 'D. Oregon'},
    'paeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Pennsylvania',
             'parent': None,
             'short_name': 'E.D. Pennsylvania'},
    'paed': {'type': 'district',
             'full_name': 'District Court, E.D. Pennsylvania',
             'parent': 'ca3',
             'short_name': 'E.D. Pennsylvania'},
    'pamb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. Pennsylvania',
             'parent': None,
             'short_name': 'M.D. Pennsylvania'},
    'pamd': {'type': 'district',
             'full_name': 'District Court, M.D. Pennsylvania',
             'parent': 'ca3',
             'short_name': 'M.D. Pennsylvania'},
    'pawb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Pennsylvania',
             'parent': None,
             'short_name': 'W.D. Pennsylvania'},
    'pawd': {'type': 'district',
             'full_name': 'District Court, W.D. Pennsylvania',
             'parent': 'ca3',
             'short_name': 'W.D. Pennsylvania'},
    'prb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Puerto Rico',
            'parent': None,
            'short_name': 'D. Puerto Rico'},
    'prd': {'type': 'district',
            'full_name': 'District Court, D. Puerto Rico',
            'parent': 'ca1',
            'short_name': 'D. Puerto Rico'},
    'rib': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Rhode Island',
            'parent': None,
            'short_name': 'D. Rhode Island'},
    'rid': {'type': 'district',
            'full_name': 'District Court, D. Rhode Island',
            'parent': 'ca1',
            'short_name': 'D. Rhode Island'},
    'scb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. South Carolina',
            'parent': None,
            'short_name': 'D. South Carolina'},
    'scd': {'type': 'district',
            'full_name': 'District Court, D. South Carolina',
            'parent': 'ca4',
            'short_name': 'D. South Carolina'},
    'scotus': {'type': 'appellate',
               'full_name': 'Supreme Court of the United States',
               'parent': None,
               'short_name': 'Supreme Court'},
    'sdb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. South Dakota',
            'parent': None,
            'short_name': 'D. South Dakota'},
    'sdd': {'type': 'district',
            'full_name': 'District Court, D. South Dakota',
            'parent': 'ca8',
            'short_name': 'D. South Dakota'},
    'tneb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Tennessee',
             'parent': None,
             'short_name': 'E.D. Tennessee'},
    'tned': {'type': 'district',
             'full_name': 'District Court, E.D. Tennessee',
             'parent': 'ca6',
             'short_name': 'E.D. Tennessee'},
    'tnmb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, M.D. Tennessee',
             'parent': None,
             'short_name': 'M.D. Tennessee'},
    'tnmd': {'type': 'district',
             'full_name': 'District Court, M.D. Tennessee',
             'parent': 'ca6',
             'short_name': 'M.D. Tennessee'},
    'tnwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Tennessee',
             'parent': None,
             'short_name': 'W.D. Tennessee'},
    'tnwd': {'type': 'district',
             'full_name': 'District Court, W.D. Tennessee',
             'parent': 'ca6',
             'short_name': 'W.D. Tennessee'},
    'txeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Texas',
             'parent': None,
             'short_name': 'E.D. Texas'},
    'txed': {'type': 'district',
             'full_name': 'District Court, E.D. Texas',
             'parent': 'ca5',
             'short_name': 'E.D. Texas'},
    'txnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. Texas',
             'parent': None,
             'short_name': 'N.D. Texas'},
    'txnd': {'type': 'district',
             'full_name': 'District Court, N.D. Texas',
             'parent': 'ca5',
             'short_name': 'N.D. Texas'},
    'txsb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. Texas',
             'parent': None,
             'short_name': 'S.D. Texas'},
    'txsd': {'type': 'district',
             'full_name': 'District Court, S.D. Texas',
             'parent': 'ca5',
             'short_name': 'S.D. Texas'},
    'txwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Texas',
             'parent': None,
             'short_name': 'W.D. Texas'},
    'txwd': {'type': 'district',
             'full_name': 'District Court, W.D. Texas',
             'parent': 'ca5',
             'short_name': 'W.D. Texas'},
    'utb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Utah',
            'parent': None,
            'short_name': 'D. Utah'},
    'utd': {'type': 'district',
            'full_name': 'District Court, D. Utah',
            'parent': 'ca10',
            'short_name': 'D. Utah'},
    'vaeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Virginia',
             'parent': None,
             'short_name': 'E.D. Virginia'},
    'vaed': {'type': 'district',
             'full_name': 'District Court, E.D. Virginia',
             'parent': 'ca4',
             'short_name': 'E.D. Virginia'},
    'vawb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Virginia',
             'parent': None,
             'short_name': 'W.D. Virginia'},
    'vawd': {'type': 'district',
             'full_name': 'District Court, W.D. Virginia',
             'parent': 'ca4',
             'short_name': 'W.D. Virginia'},
    'vib': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Virgin Islands',
            'parent': None,
            'short_name': 'D. Virgin Islands'},
    'vid': {'type': 'district',
            'full_name': 'District Court, Virgin Islands',
            'parent': 'ca3',
            'short_name': 'Virgin Islands'},
    'vtb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Vermont',
            'parent': None,
            'short_name': 'D. Vermont'},
    'vtd': {'type': 'district',
            'full_name': 'District Court, D. Vermont',
            'parent': 'ca2',
            'short_name': 'D. Vermont'},
    'waeb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Washington',
             'parent': None,
             'short_name': 'E.D. Washington'},
    'waed': {'type': 'district',
             'full_name': 'District Court, E.D. Washington',
             'parent': 'ca9',
             'short_name': 'E.D. Washington'},
    'wawb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Washington',
             'parent': None,
             'short_name': 'W.D. Washington'},
    'wawd': {'type': 'district',
             'full_name': 'District Court, W.D. Washington',
             'parent': 'ca9',
             'short_name': 'W.D. Washington'},
    'wieb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, E.D. Wisconsin',
             'parent': None,
             'short_name': 'E.D. Wisconsin'},
    'wied': {'type': 'district',
             'full_name': 'District Court, E.D. Wisconsin',
             'parent': 'ca7',
             'short_name': 'E.D. Wisconsin'},
    'wiwb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, W.D. Wisconsin',
             'parent': None,
             'short_name': 'W.D. Wisconsin'},
    'wiwd': {'type': 'district',
             'full_name': 'District Court, W.D. Wisconsin',
             'parent': 'ca7',
             'short_name': 'W.D. Wisconsin'},
    'wvnb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, N.D. West Virginia',
             'parent': None,
             'short_name': 'N.D. West Virginia'},
    'wvnd': {'type': 'district',
             'full_name': 'District Court, N.D. West Virginia',
             'parent': 'ca4',
             'short_name': 'N.D. West Virginia'},
    'wvsb': {'type': 'bankruptcy',
             'full_name': 'United States Bankruptcy Court, S.D. West Virginia',
             'parent': None,
             'short_name': 'S.D. West Virginia'},
    'wvsd': {'type': 'district',
             'full_name': 'District Court, S.D. West Virginia',
             'parent': 'ca4',
             'short_name': 'S.D. West Virginia'},
    'wyb': {'type': 'bankruptcy',
            'full_name': 'United States Bankruptcy Court, D. Wyoming',
            'parent': None,
            'short_name': 'D. Wyoming'},
    'wyd': {'type': 'district',
            'full_name': 'District Court, D. Wyoming',
            'parent': 'ca10',
            'short_name': 'D. Wyoming'}}
